version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: friday
    commit-message:
      prefix: "ci: 👷 "
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: friday
    commit-message:
      prefix: "build: ⬆️ "
